# This is a basic workflow to help you get started with Actions

name: Build deployAVDSessionHostReplacer bicep file into ARM

# Controls when the workflow will run
on:
  push:
    paths:
      - 'deploy/bicep/DeployAVDSessionHostReplacer.bicep'
  workflow_dispatch:
    inputs:
      messages:
       description: 'Why are you running manually?'
       required: false
       default: 'Manual Run'
jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
        with:
          ref: ${{ github.head_ref}}

      - name: Build Bicep File
        shell: pwsh
        run: |
          bicep build deploy/bicep/DeployAVDSessionHostReplacer.bicep --outfile deploy/arm/DeployAVDSessionHostReplacer.json

      - name: publish
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update for ARM templates